### ISSUE TITLE
Looping if output folder is not empty

### ISSUE THREAD

**Issue by iljavh** [UMCUGenetics/DIMS#12]
If the output folder at the time of the start of a run has already some results in it, the pipeline loops endlessly with the same jobs. Should not happen or explain in the error solving documentation that this could happen.

**Comment by poofcakes** [comment]
I believe this only happens when the folder that is used already contains output from a completely finished run, so one that has a created "done" file to show to either the positive or negative branch that the other branch has already finished and the finalisation of the pipeline can be initiated (excel creation and cleanup). The GUI contains a check that existing folders cannot be used at all, so this is then not an issue. When running without GUI, one needs to just not use such a folder as output folder in general; that is the case with pretty much any software, especially if the software at certain points reads from the output folder to know which steps to take. 

One solution to prevent this user error is to add in a warning (eg. "are you sure you want to use x folder", and then a yes/no user input) when attempting to use an existing folder as output folder. Despite the GUI not really being able to do manual user inputs in this way as the process is automated, this solution should not cause issues for the GUI, as the folder cannot exist in the first place before you can run the pipeline with the GUI. Still, a parameter could be added to ignore the warning in case someone happens to create a folder with the exact same name right after the check and right before starting the pipeline.

**Comment by FiniDG-HAN** [comment]
Updated in the DIMS SOP on how to handle this problem and even more important, how to Prevent this problem from happening. This is not a relevant to fix right now, because it will never happen if you use the GUI (should be 99% of the time) and without GUI the DIMS pipeline will always be started by a bioinformatician. This is not an issue that will happen often. I might reopen this if the problem occurs more often or when additional bugs appear.
