### ISSUE TITLE
Data on hpc

### ISSUE THREAD

**Issue by iljavh** [UMCUGenetics/DIMS#14]
Generate a consensus on when which DIMS input and output data is to be deleted from hpc and where what data is where stored (back-up folder) on the long run.

**Comment by FiniDG-HAN** [comment]
Maybe also have a consensus on which data to share to the analists who have no access to the HPC. Which files will be put on their own LAB drive?

**Comment by FiniDG-HAN** [comment]
Consensus was made.
If the analist has access to HPC, he of she will delete "old" data from the HPC themselves
The bioinformatician may delete these after a period of one month (unless asked otherwise)
The runs done by the bioinformatician may be deleted by a bioinformatician after one month (unless asked otherwise)

This information will be available in the "DIMS with GUI" and "DIMS without GUI" SOPs
